local M = {}

M.colors = {
    bg = "#0B0B0F",             -- Main editor background
    fg = "#E6E6E6",             -- Default text color
    line_nr = "#32333B",        -- Line number color
    active_line_nr = "#E6E6E6", -- Active line number color
    comment = "#46474F",        -- Comments
    selection = "#2C2C31",      -- Selection background (adjusted from #EAEC8A21)
    selection_highlight = "#1A1A1F", -- Selection highlight background (adjusted from #FFFFFF08)
    word_highlight = "#2C2C31",     -- Word highlight background (adjusted from #EAEC8A16)
    yellow = "#E6E7A3",         -- Light yellow for functions, etc.
    red = "#D84F68",            -- Red for errors and deleted content
    orange = "#F9B98C",         -- Peachy color for numbers and constants
    purple = "#9592A4",         -- Muted purple
    blue = "#479FFA",           -- Bright blue for links
    gray = "#9099A1",           -- Grayish for keywords
    teal = "#54C0A3",           -- Teal for attributes
    bracket = "#5C6974",        -- Dark gray for brackets
    dark_gray = "#2C2C31",      -- For input background
    black = "#000000",          -- Pure black
    diff_add_bg = "#1A1A1F",    -- Background for added text in diffs (adjusted from #E6E6E615)
    diff_del_bg = "#2C1A1A",    -- Background for removed text in diffs (adjusted from #D84F6815)
    warning = "#FFA16C",        -- Warning color
    error = "#FF5C5C",          -- Error color
    hint = "#4EBE96",           -- Hint color
    info = "#6A7782",           -- Info color
    sidebar_bg = "#0B0B0F",     -- Sidebar background
    sidebar_fg = "#C1C1C1",     -- Sidebar text color
    sidebar_title = "#9592A4",  -- Sidebar title color
    list_active = "#232323",    -- List active selection background
    list_inactive = "#232323",  -- List inactive selection background
    list_hover = "#1A1A1F",     -- List hover background (adjusted from #FFFFFF08)
    input_bg = "#2C2C31",       -- Input background
    input_fg = "#E6E6E6",       -- Input text color
    hover_bg = "#161616",       -- Hover widget background
    hover_border = "#282828",   -- Hover widget border
    scrollbar_bg = "#343434",   -- Scrollbar background (adjusted from #34343480)
    scrollbar_hover = "#343434", -- Scrollbar hover background
    quick_input_bg = "#2C2C31", -- Quick input background
    quick_input_fg = "#C1C1C1", -- Quick input text
    quick_input_focus = "#1A1A1F", -- Quick input focus background (adjusted from #FFFFFF16)
    description_fg = "#C1C1C1", -- Description text color
    bracket_1 = "#5C6974",      -- Bracket pair color 1
    bracket_2 = "#6E678E",      -- Bracket pair color 2
    bracket_3 = "#6A7782",      -- Bracket pair color 3
    bracket_4 = "#6A7782",      -- Bracket pair color 4
    bracket_5 = "#6A7782",      -- Bracket pair color 5
    bracket_6 = "#6A7782",      -- Bracket pair color 6
    bracket_unexpected = "#6A7782", -- Unexpected bracket color
}

return M 